spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/learn_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:  #数据库连接池配置
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379
